logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      base-path: /app 

security:
  basic:
    enabled: true
  user: fc
  password: fc

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.api.johnluetke.com:3306/FindCheeseheads?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto: none
  mvc:
    dispatch-options-request: true